export const types = {
    TOKEN_SET: 'TOKEN_SET',
    TOKEN_GET: 'TOKEN_GET',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_REFRESHED: 'TOKEN_REFRESHED',
    REFRESH_TOKEN_SET: 'REFRESH_TOKEN_SET',

    DASHBOARD_REQUEST: 'DASHBOARD_REQUEST',
    DASHBOARD_SET: 'DASHBOARD_SET',
    DASHBOARD_UPDATE_BUDGETS: 'DASHBOARD_UPDATE_BUDGETS',

    EXPENSES_REQUEST: 'EXPENSES_REQUEST',
    EXPENSES_SET: 'EXPENSES_SET',

    BUDGETS_REQUEST: 'BUDGETS_REQUEST',
    BUDGETS_SET: 'BUDGETS_SET',

    POPUP_ERROR_SET: 'POPUP_ERROR_SET',
    POPUP_ERROR_REMOVE: 'POPUP_ERROR_REMOVE',

    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT'
};