export const types = {
    TOKEN_SET: 'TOKEN_SET',
    TOKEN_GET: 'TOKEN_GET',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_REFRESHED: 'TOKEN_REFRESHED',
    REFRESH_TOKEN_SET: 'REFRESH_TOKEN_SET',

    DASHBOARD_REQUEST: 'DASHBOARD_REQUEST',
    DASHBOARD_SET: 'DASHBOARD_SET',

    POPUP_ERROR_SET: 'POPUP_ERROR_SET',
    POPUP_ERROR_REMOVE: 'POPUP_ERROR_REMOVE',

    USER_LOGIN: 'USER_LOGIN',
};